on: 
  repository_dispatch:
    types:
      - resource-published
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "Just published: `${{ github.event.client_payload.path }}`",
            }
