on: 
  repository_dispatch:
    types:
      - resource-published
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Status: ${{ github.event.client_payload.status }}"
        echo "Path: ${{ github.event.client_payload.path }}"
  slack:
    uses: slackapi/slack-github-action
    with:
      slack-message: ${{ github.event.client_payload.path }} has been published.
